---
fps: 25
assets:
 background:
  src: assets/background.png
  fps: 24
  x: 0
  y: 0
 badger:
  src: assets/dickbutt-badger.png
  fps: 12
  duration: 4.5
  x: 0
  y: 0
 mushroom:
  src: assets/mushroom-goatse.png
  fps: 2
  duration: 1.5
  x: 0
  y: 0
 snake:
  src: assets/cup.png
  fps: 12
  duration: 6
  x: 0
  y: 75
scenes:
 - badgers
 - mushrooms
 - badgers
 - mushrooms
 - badgers
 - snake
timeline:
 -
  - 20
  - 300
  - 1
 -
  - 250
  - 285
  - 0.92
 -
  - 500
  - 235
  - 0.84
 -
  - 135
  - 200
  - 0.76
 -
  - 345
  - 185
  - 0.68
 -
  - 223
  - 150
  - 0.60
 -
  - 0
  - 125
  - 0.52
 #-
  #- 340
  #- 124
  #- 0.48
 -
  - 500
  - 100
  - 0.44
 -
  - 90
  - 95
  - 0.36
 -
  - 245
  - 90
  - 0.28
 -
  - 400
  - 85
  - 0.20
 -
  - 315
  - 80
  - 0.12
